apiVersion: apps/v1
kind: Deployment
metadata:
  name: itl-summary
  labels:
    k8s-app: itl-summary
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: itl-summary
  template:
    metadata:
      labels:
        k8s-app: itl-summary
    spec:
      containers:
      - name: itl-summary
        image: d0m182/in-the-loop-qa:0.0.3
        ports:
        - containerPort: 5000
          protocol: TCP


---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: itl-summary
  name: itl-summary
  namespace: default
spec:
  ports:
    - port: 443
      targetPort: 5000
  type: NodePort
  selector:
    k8s-app: itl-summary