apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: itl-qa
  name: itl-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itl-qa
  template:
    metadata:
      labels:
        app: itl-qa
    spec:
      containers:
      - image: bf-dtr.aws.capgemini-ips.com/docker-datacenter/qa:0.0.3
        name: itl-qa
      nodeSelector:
        nodetype: gpu
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itl-qa
  name: itl-qa
spec:
  selector:
    app: itl-qa
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: itl-summary
  name: itl-summary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itl-summary
  template:
    metadata:
      labels:
        app: itl-summary
    spec:
      containers:
      - image: bf-dtr.aws.capgemini-ips.com/docker-datacenter/summary:0.0.5
        name: itl-summary
      nodeSelector:
        nodetype: gpu
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itl-summary
  name: itl-summary
spec:
  selector:
    app: itl-summary
  ports:
  - name: 5000-5000
    port: 5000
    protocol: TCP
    targetPort: 5000
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: itl-web-ui
  name: itl-web-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itl-web-ui
  template:
    metadata:
      labels:
        app: itl-web-ui
    spec:
      containers:
      - image: bf-dtr.aws.capgemini-ips.com/docker-datacenter/web-ui:0.0.7
        name: itl-web-ui
        env:
        - name: SUMMARY_URL
          value: "itl-summary.default.svc.cluster.local"
        - name: SUMMARY_PORT
          value: "5000"
        - name: QA_URL
          value: "itl-qa.default.svc.cluster.local"
        - name: QA_PORT
          value: "5000"
        - name: DB_ADDR
          value: "itl-postges.default.svc.cluster.local"
        - name: DB_NAME
          value: "ai"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itl-web-ui
  name: itl-web-ui
spec:
  selector:
    app: itl-web-ui
  ports:
  - name: 32345-5000
    port: 32345
    protocol: TCP
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: itl-postgres
  name: itl-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: itl-postgres
  template:
    metadata:
      labels:
        app: itl-postgres
    spec:
      containers:
      - image: bf-dtr.aws.capgemini-ips.com/docker-datacenter/postgres:9
        name: itl-postgres
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: itl-postgres
  name: itl-postgres
spec:
  selector:
    app: itl-postgres
  ports:
  - name: 5432-5432
    port: 5432
    protocol: TCP
    targetPort: 5432